server:
  context-path: /miniits
  port: 8080
  tomcat:
    max-http-header-size: 100000000

management:
  port: ${server.port}

info:
  app:
    name: MiniIts
    description: 迷你科技
    version: 1.0.0

spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 8
    min-idle: 8
    validation-query: SELECT 1
    test-on-borrow: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/miniits?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123